
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class CamImageSettings
	{
		private global::Gtk.Table table3;
		
		private global::Gtk.Button btnReset;
		
		private global::Gtk.HScale hscaleBrightness;
		
		private global::Gtk.HScale hscaleHue;
		
		private global::Gtk.HScale hscaleSaturation;
		
		private global::Gtk.HScale hscaleSharpness;
		
		private global::Gtk.Label lblBrightness;
		
		private global::Gtk.Label lblHue;
		
		private global::Gtk.Label lblSaturation;
		
		private global::Gtk.Label lblSharpness;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.CamImageSettings
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xCom.CamManager.CamImageSettings";
			// Container child xCom.CamManager.CamImageSettings.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.btnReset = new global::Gtk.Button ();
			this.btnReset.CanFocus = true;
			this.btnReset.Name = "btnReset";
			this.btnReset.UseUnderline = true;
			this.btnReset.Label = "Reset";
			this.table3.Add (this.btnReset);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnReset]));
			w1.TopAttach = ((uint)(4));
			w1.BottomAttach = ((uint)(5));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(0));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hscaleBrightness = new global::Gtk.HScale (null);
			this.hscaleBrightness.CanFocus = true;
			this.hscaleBrightness.Name = "hscaleBrightness";
			this.hscaleBrightness.Adjustment.Upper = 100D;
			this.hscaleBrightness.Adjustment.PageIncrement = 10D;
			this.hscaleBrightness.Adjustment.StepIncrement = 1D;
			this.hscaleBrightness.DrawValue = true;
			this.hscaleBrightness.Digits = 0;
			this.hscaleBrightness.ValuePos = ((global::Gtk.PositionType)(2));
			this.table3.Add (this.hscaleBrightness);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.hscaleBrightness]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hscaleHue = new global::Gtk.HScale (null);
			this.hscaleHue.CanFocus = true;
			this.hscaleHue.Name = "hscaleHue";
			this.hscaleHue.Adjustment.Upper = 100D;
			this.hscaleHue.Adjustment.PageIncrement = 10D;
			this.hscaleHue.Adjustment.StepIncrement = 1D;
			this.hscaleHue.DrawValue = true;
			this.hscaleHue.Digits = 0;
			this.hscaleHue.ValuePos = ((global::Gtk.PositionType)(2));
			this.table3.Add (this.hscaleHue);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.hscaleHue]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hscaleSaturation = new global::Gtk.HScale (null);
			this.hscaleSaturation.CanFocus = true;
			this.hscaleSaturation.Name = "hscaleSaturation";
			this.hscaleSaturation.Adjustment.Upper = 100D;
			this.hscaleSaturation.Adjustment.PageIncrement = 10D;
			this.hscaleSaturation.Adjustment.StepIncrement = 1D;
			this.hscaleSaturation.DrawValue = true;
			this.hscaleSaturation.Digits = 0;
			this.hscaleSaturation.ValuePos = ((global::Gtk.PositionType)(2));
			this.table3.Add (this.hscaleSaturation);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.hscaleSaturation]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hscaleSharpness = new global::Gtk.HScale (null);
			this.hscaleSharpness.CanFocus = true;
			this.hscaleSharpness.Name = "hscaleSharpness";
			this.hscaleSharpness.Adjustment.Upper = 100D;
			this.hscaleSharpness.Adjustment.PageIncrement = 10D;
			this.hscaleSharpness.Adjustment.StepIncrement = 1D;
			this.hscaleSharpness.DrawValue = true;
			this.hscaleSharpness.Digits = 0;
			this.hscaleSharpness.ValuePos = ((global::Gtk.PositionType)(2));
			this.table3.Add (this.hscaleSharpness);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.hscaleSharpness]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lblBrightness = new global::Gtk.Label ();
			this.lblBrightness.Name = "lblBrightness";
			this.lblBrightness.Xalign = 0F;
			this.lblBrightness.LabelProp = "Brightness";
			this.table3.Add (this.lblBrightness);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.lblBrightness]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lblHue = new global::Gtk.Label ();
			this.lblHue.Name = "lblHue";
			this.lblHue.Xalign = 0F;
			this.lblHue.LabelProp = "Hue";
			this.table3.Add (this.lblHue);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.lblHue]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lblSaturation = new global::Gtk.Label ();
			this.lblSaturation.Name = "lblSaturation";
			this.lblSaturation.Xalign = 0F;
			this.lblSaturation.LabelProp = "Saturation";
			this.table3.Add (this.lblSaturation);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.lblSaturation]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lblSharpness = new global::Gtk.Label ();
			this.lblSharpness.Name = "lblSharpness";
			this.lblSharpness.Xalign = 0F;
			this.lblSharpness.LabelProp = "Sharpness";
			this.table3.Add (this.lblSharpness);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.lblSharpness]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.hscaleSharpness.ValueChanged += new global::System.EventHandler (this.OnHscaleSharpnessValueChanged);
			this.hscaleSaturation.ValueChanged += new global::System.EventHandler (this.OnHscaleSaturationValueChanged);
			this.hscaleHue.ValueChanged += new global::System.EventHandler (this.OnHscaleHueValueChanged);
			this.hscaleBrightness.ValueChanged += new global::System.EventHandler (this.OnHscaleBrightnessValueChanged);
			this.btnReset.Clicked += new global::System.EventHandler (this.OnBtnResetClicked);
		}
	}
}
