
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class CamVideoSettings
	{
		private global::Gtk.Table table4;
		
		private global::Gtk.Button btnSave;
		
		private global::Gtk.Button btnSetStreamType;
		
		private global::Gtk.ComboBox cmbBitrate;
		
		private global::Gtk.ComboBox cmbFramerate;
		
		private global::Gtk.ComboBox cmbGroupOfPics;
		
		private global::Gtk.ComboBox cmbResolution;
		
		private global::Gtk.ComboBox cmbStreamKind;
		
		private global::Gtk.ComboBox cmbStreamType;
		
		private global::Gtk.ComboBox cmbVariableBitrate;
		
		private global::Gtk.Label lblBitrate;
		
		private global::Gtk.Label lblFramerate;
		
		private global::Gtk.Label lblGroupOfPics;
		
		private global::Gtk.Label lblResolution;
		
		private global::Gtk.Label lblStreamKind;
		
		private global::Gtk.Label lblStreamType;
		
		private global::Gtk.Label lblVariableBitrate;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.CamVideoSettings
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xCom.CamManager.CamVideoSettings";
			// Container child xCom.CamManager.CamVideoSettings.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(9)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = "Save";
			this.table4.Add (this.btnSave);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table4 [this.btnSave]));
			w1.TopAttach = ((uint)(8));
			w1.BottomAttach = ((uint)(9));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(1));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.btnSetStreamType = new global::Gtk.Button ();
			this.btnSetStreamType.CanFocus = true;
			this.btnSetStreamType.Name = "btnSetStreamType";
			this.btnSetStreamType.UseUnderline = true;
			this.btnSetStreamType.Label = "Set";
			this.table4.Add (this.btnSetStreamType);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4 [this.btnSetStreamType]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(0));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbBitrate = global::Gtk.ComboBox.NewText ();
			this.cmbBitrate.Name = "cmbBitrate";
			this.table4.Add (this.cmbBitrate);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbBitrate]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbFramerate = global::Gtk.ComboBox.NewText ();
			this.cmbFramerate.Name = "cmbFramerate";
			this.table4.Add (this.cmbFramerate);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbFramerate]));
			w4.TopAttach = ((uint)(5));
			w4.BottomAttach = ((uint)(6));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbGroupOfPics = global::Gtk.ComboBox.NewText ();
			this.cmbGroupOfPics.Name = "cmbGroupOfPics";
			this.table4.Add (this.cmbGroupOfPics);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbGroupOfPics]));
			w5.TopAttach = ((uint)(6));
			w5.BottomAttach = ((uint)(7));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbResolution = global::Gtk.ComboBox.NewText ();
			this.cmbResolution.AppendText ("HD");
			this.cmbResolution.AppendText ("VGA(640*480)");
			this.cmbResolution.AppendText ("VGA(640*360)");
			this.cmbResolution.AppendText ("QVGA(320*240)");
			this.cmbResolution.AppendText ("QVGA(320*180)");
			this.cmbResolution.Name = "cmbResolution";
			this.table4.Add (this.cmbResolution);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbResolution]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbStreamKind = global::Gtk.ComboBox.NewText ();
			this.cmbStreamKind.AppendText ("Main Stream");
			this.cmbStreamKind.AppendText ("Sub Stream");
			this.cmbStreamKind.Name = "cmbStreamKind";
			this.table4.Add (this.cmbStreamKind);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbStreamKind]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbStreamType = global::Gtk.ComboBox.NewText ();
			this.cmbStreamType.AppendText ("HD Modus");
			this.cmbStreamType.AppendText ("Equilibrium");
			this.cmbStreamType.AppendText ("VGA");
			this.cmbStreamType.AppendText ("Custom");
			this.cmbStreamType.Name = "cmbStreamType";
			this.table4.Add (this.cmbStreamType);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbStreamType]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.cmbVariableBitrate = global::Gtk.ComboBox.NewText ();
			this.cmbVariableBitrate.AppendText ("Yes");
			this.cmbVariableBitrate.AppendText ("No");
			this.cmbVariableBitrate.Name = "cmbVariableBitrate";
			this.table4.Add (this.cmbVariableBitrate);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4 [this.cmbVariableBitrate]));
			w9.TopAttach = ((uint)(7));
			w9.BottomAttach = ((uint)(8));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblBitrate = new global::Gtk.Label ();
			this.lblBitrate.Name = "lblBitrate";
			this.lblBitrate.Xalign = 0F;
			this.lblBitrate.LabelProp = "Bitrate";
			this.table4.Add (this.lblBitrate);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblBitrate]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblFramerate = new global::Gtk.Label ();
			this.lblFramerate.Name = "lblFramerate";
			this.lblFramerate.Xalign = 0F;
			this.lblFramerate.LabelProp = "Framerate";
			this.table4.Add (this.lblFramerate);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblFramerate]));
			w11.TopAttach = ((uint)(5));
			w11.BottomAttach = ((uint)(6));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblGroupOfPics = new global::Gtk.Label ();
			this.lblGroupOfPics.Name = "lblGroupOfPics";
			this.lblGroupOfPics.Xalign = 0F;
			this.lblGroupOfPics.LabelProp = "Group of Picture";
			this.table4.Add (this.lblGroupOfPics);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblGroupOfPics]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblResolution = new global::Gtk.Label ();
			this.lblResolution.Name = "lblResolution";
			this.lblResolution.Xalign = 0F;
			this.lblResolution.LabelProp = "Resolution";
			this.table4.Add (this.lblResolution);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblResolution]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblStreamKind = new global::Gtk.Label ();
			this.lblStreamKind.Name = "lblStreamKind";
			this.lblStreamKind.Xalign = 0F;
			this.lblStreamKind.LabelProp = "Stream Kind";
			this.table4.Add (this.lblStreamKind);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblStreamKind]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblStreamType = new global::Gtk.Label ();
			this.lblStreamType.Name = "lblStreamType";
			this.lblStreamType.Xalign = 0F;
			this.lblStreamType.LabelProp = "Stream Type";
			this.table4.Add (this.lblStreamType);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblStreamType]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblVariableBitrate = new global::Gtk.Label ();
			this.lblVariableBitrate.Name = "lblVariableBitrate";
			this.lblVariableBitrate.Xalign = 0F;
			this.lblVariableBitrate.LabelProp = "Variable Bitrate";
			this.table4.Add (this.lblVariableBitrate);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblVariableBitrate]));
			w16.TopAttach = ((uint)(7));
			w16.BottomAttach = ((uint)(8));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.cmbStreamType.Changed += new global::System.EventHandler (this.OnCmbStreamTypeChanged);
			this.cmbStreamKind.Changed += new global::System.EventHandler (this.OnCmbStreamKindChanged);
			this.btnSetStreamType.Clicked += new global::System.EventHandler (this.OnBtnSetStreamTypeClicked);
			this.btnSave.Clicked += new global::System.EventHandler (this.OnBtnSaveClicked);
		}
	}
}
