
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class CamConnection
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnConnect;
		
		private global::Gtk.Label lblIpDns;
		
		private global::Gtk.Label lblPassword;
		
		private global::Gtk.Label lblPort;
		
		private global::Gtk.Label lblUserName;
		
		private global::Gtk.Entry txtIpDns;
		
		private global::Gtk.Entry txtPassword;
		
		private global::Gtk.Entry txtPort;
		
		private global::Gtk.Entry txtUserName;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.CamConnection
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xCom.CamManager.CamConnection";
			// Container child xCom.CamManager.CamConnection.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnConnect = new global::Gtk.Button ();
			this.btnConnect.CanFocus = true;
			this.btnConnect.Name = "btnConnect";
			this.btnConnect.UseUnderline = true;
			this.btnConnect.Label = "Connect";
			this.table1.Add (this.btnConnect);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnConnect]));
			w1.TopAttach = ((uint)(4));
			w1.BottomAttach = ((uint)(5));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(1));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblIpDns = new global::Gtk.Label ();
			this.lblIpDns.Name = "lblIpDns";
			this.lblIpDns.Xalign = 0F;
			this.lblIpDns.LabelProp = "IP or DNS:";
			this.table1.Add (this.lblIpDns);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblIpDns]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblPassword = new global::Gtk.Label ();
			this.lblPassword.Name = "lblPassword";
			this.lblPassword.Xalign = 0F;
			this.lblPassword.LabelProp = "Password:";
			this.table1.Add (this.lblPassword);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblPassword]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblPort = new global::Gtk.Label ();
			this.lblPort.Name = "lblPort";
			this.lblPort.Xalign = 0F;
			this.lblPort.LabelProp = "Port:";
			this.table1.Add (this.lblPort);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblPort]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblUserName = new global::Gtk.Label ();
			this.lblUserName.Name = "lblUserName";
			this.lblUserName.Xalign = 0F;
			this.lblUserName.LabelProp = "Username";
			this.table1.Add (this.lblUserName);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblUserName]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtIpDns = new global::Gtk.Entry ();
			this.txtIpDns.CanFocus = true;
			this.txtIpDns.Name = "txtIpDns";
			this.txtIpDns.IsEditable = true;
			this.txtIpDns.InvisibleChar = '●';
			this.table1.Add (this.txtIpDns);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtIpDns]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtPassword = new global::Gtk.Entry ();
			this.txtPassword.CanFocus = true;
			this.txtPassword.Name = "txtPassword";
			this.txtPassword.IsEditable = true;
			this.txtPassword.Visibility = false;
			this.txtPassword.InvisibleChar = '●';
			this.table1.Add (this.txtPassword);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPassword]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtPort = new global::Gtk.Entry ();
			this.txtPort.CanFocus = true;
			this.txtPort.Name = "txtPort";
			this.txtPort.IsEditable = true;
			this.txtPort.InvisibleChar = '●';
			this.table1.Add (this.txtPort);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPort]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtUserName = new global::Gtk.Entry ();
			this.txtUserName.CanFocus = true;
			this.txtUserName.Name = "txtUserName";
			this.txtUserName.IsEditable = true;
			this.txtUserName.InvisibleChar = '●';
			this.table1.Add (this.txtUserName);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtUserName]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnConnect.Clicked += new global::System.EventHandler (this.OnBtnConnectClicked);
		}
	}
}
