
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class BaseWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.BaseWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xCom.CamManager.BaseWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
