
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class CamNavigation
	{
		private global::Gtk.Table table2;
		
		private global::Gtk.Button btnAddPreset;
		
		private global::Gtk.Button btnBottom;
		
		private global::Gtk.Button btnBottomLeft;
		
		private global::Gtk.Button btnBottomRight;
		
		private global::Gtk.Button btnLeft;
		
		private global::Gtk.Button btnMiddle;
		
		private global::Gtk.Button btnPlayPreset;
		
		private global::Gtk.Button btnRemovePreset;
		
		private global::Gtk.Button btnRight;
		
		private global::Gtk.Button btnTop;
		
		private global::Gtk.Button btnTopLeft;
		
		private global::Gtk.Button btnTopRight;
		
		private global::Gtk.CheckButton chkFlip;
		
		private global::Gtk.CheckButton chkMirror;
		
		private global::Gtk.CheckButton chkNightMode;
		
		private global::Gtk.ComboBox cmbPresetSettings;
		
		private global::Gtk.Label lblPreset;
		
		private global::Gtk.Label lblPresetHeader;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.CamNavigation
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xCom.CamManager.CamNavigation";
			// Container child xCom.CamManager.CamNavigation.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(7)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.btnAddPreset = new global::Gtk.Button ();
			this.btnAddPreset.CanFocus = true;
			this.btnAddPreset.Name = "btnAddPreset";
			this.btnAddPreset.UseUnderline = true;
			this.btnAddPreset.Label = "Add ...";
			this.table2.Add (this.btnAddPreset);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnAddPreset]));
			w1.TopAttach = ((uint)(6));
			w1.BottomAttach = ((uint)(7));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnBottom = new global::Gtk.Button ();
			this.btnBottom.CanFocus = true;
			this.btnBottom.Name = "btnBottom";
			this.btnBottom.UseUnderline = true;
			this.btnBottom.Label = "Bottom";
			this.table2.Add (this.btnBottom);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnBottom]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnBottomLeft = new global::Gtk.Button ();
			this.btnBottomLeft.CanFocus = true;
			this.btnBottomLeft.Name = "btnBottomLeft";
			this.btnBottomLeft.UseUnderline = true;
			this.btnBottomLeft.Label = "Bottom Left";
			this.table2.Add (this.btnBottomLeft);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnBottomLeft]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			// Container child table2.Gtk.Table+TableChild
			this.btnBottomRight = new global::Gtk.Button ();
			this.btnBottomRight.CanFocus = true;
			this.btnBottomRight.Name = "btnBottomRight";
			this.btnBottomRight.UseUnderline = true;
			this.btnBottomRight.Label = "Bottom Right";
			this.table2.Add (this.btnBottomRight);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnBottomRight]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnLeft = new global::Gtk.Button ();
			this.btnLeft.CanFocus = true;
			this.btnLeft.Name = "btnLeft";
			this.btnLeft.UseUnderline = true;
			this.btnLeft.Label = "Left";
			this.table2.Add (this.btnLeft);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnLeft]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.btnMiddle = new global::Gtk.Button ();
			this.btnMiddle.CanFocus = true;
			this.btnMiddle.Name = "btnMiddle";
			this.btnMiddle.UseUnderline = true;
			this.btnMiddle.Label = "Center";
			this.table2.Add (this.btnMiddle);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnMiddle]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnPlayPreset = new global::Gtk.Button ();
			this.btnPlayPreset.CanFocus = true;
			this.btnPlayPreset.Name = "btnPlayPreset";
			this.btnPlayPreset.UseUnderline = true;
			this.btnPlayPreset.Label = "Play ...";
			this.table2.Add (this.btnPlayPreset);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnPlayPreset]));
			w7.TopAttach = ((uint)(6));
			w7.BottomAttach = ((uint)(7));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnRemovePreset = new global::Gtk.Button ();
			this.btnRemovePreset.CanFocus = true;
			this.btnRemovePreset.Name = "btnRemovePreset";
			this.btnRemovePreset.UseUnderline = true;
			this.btnRemovePreset.Label = "Remove ...";
			this.table2.Add (this.btnRemovePreset);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnRemovePreset]));
			w8.TopAttach = ((uint)(6));
			w8.BottomAttach = ((uint)(7));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnRight = new global::Gtk.Button ();
			this.btnRight.CanFocus = true;
			this.btnRight.Name = "btnRight";
			this.btnRight.UseUnderline = true;
			this.btnRight.Label = "Right";
			this.table2.Add (this.btnRight);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnRight]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnTop = new global::Gtk.Button ();
			this.btnTop.CanFocus = true;
			this.btnTop.Name = "btnTop";
			this.btnTop.UseUnderline = true;
			this.btnTop.Label = "Top";
			this.table2.Add (this.btnTop);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnTop]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnTopLeft = new global::Gtk.Button ();
			this.btnTopLeft.CanFocus = true;
			this.btnTopLeft.Name = "btnTopLeft";
			this.btnTopLeft.UseUnderline = true;
			this.btnTopLeft.Label = "Top Left";
			this.table2.Add (this.btnTopLeft);
			// Container child table2.Gtk.Table+TableChild
			this.btnTopRight = new global::Gtk.Button ();
			this.btnTopRight.CanFocus = true;
			this.btnTopRight.Name = "btnTopRight";
			this.btnTopRight.UseUnderline = true;
			this.btnTopRight.Label = "Top Right";
			this.table2.Add (this.btnTopRight);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnTopRight]));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chkFlip = new global::Gtk.CheckButton ();
			this.chkFlip.CanFocus = true;
			this.chkFlip.Name = "chkFlip";
			this.chkFlip.Label = "Flip";
			this.chkFlip.DrawIndicator = true;
			this.chkFlip.UseUnderline = true;
			this.table2.Add (this.chkFlip);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkFlip]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(1));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chkMirror = new global::Gtk.CheckButton ();
			this.chkMirror.CanFocus = true;
			this.chkMirror.Name = "chkMirror";
			this.chkMirror.Label = "Mirror";
			this.chkMirror.DrawIndicator = true;
			this.chkMirror.UseUnderline = true;
			this.table2.Add (this.chkMirror);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkMirror]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(1));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chkNightMode = new global::Gtk.CheckButton ();
			this.chkNightMode.CanFocus = true;
			this.chkNightMode.Name = "chkNightMode";
			this.chkNightMode.Label = "Night Mode";
			this.chkNightMode.DrawIndicator = true;
			this.chkNightMode.UseUnderline = true;
			this.table2.Add (this.chkNightMode);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.chkNightMode]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(1));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cmbPresetSettings = global::Gtk.ComboBox.NewText ();
			this.cmbPresetSettings.Name = "cmbPresetSettings";
			this.table2.Add (this.cmbPresetSettings);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.cmbPresetSettings]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(3));
			w16.XPadding = ((uint)(1));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblPreset = new global::Gtk.Label ();
			this.lblPreset.Name = "lblPreset";
			this.lblPreset.Xalign = 0F;
			this.lblPreset.LabelProp = "Preset";
			this.table2.Add (this.lblPreset);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblPreset]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblPresetHeader = new global::Gtk.Label ();
			this.lblPresetHeader.Name = "lblPresetHeader";
			this.lblPresetHeader.Xalign = 0F;
			this.lblPresetHeader.LabelProp = "Preset Settings";
			this.table2.Add (this.lblPresetHeader);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblPresetHeader]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.RightAttach = ((uint)(3));
			w18.XPadding = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.chkNightMode.Toggled += new global::System.EventHandler (this.OnChkNightModeToggled);
			this.chkMirror.Toggled += new global::System.EventHandler (this.OnChkMirrorToggled);
			this.chkFlip.Toggled += new global::System.EventHandler (this.OnChkFlipToggled);
			this.btnTopRight.Pressed += new global::System.EventHandler (this.OnBtnTopRightPressed);
			this.btnTopRight.Released += new global::System.EventHandler (this.OnBtnTopRightReleased);
			this.btnTopLeft.Pressed += new global::System.EventHandler (this.OnBtnTopLeftPressed);
			this.btnTopLeft.Released += new global::System.EventHandler (this.OnBtnTopLeftReleased);
			this.btnTop.Pressed += new global::System.EventHandler (this.OnBtnTopPressed);
			this.btnTop.Released += new global::System.EventHandler (this.OnBtnTopReleased);
			this.btnRight.Pressed += new global::System.EventHandler (this.OnBtnRightPressed);
			this.btnRight.Released += new global::System.EventHandler (this.OnBtnRightReleased);
			this.btnRemovePreset.Clicked += new global::System.EventHandler (this.OnBtnRemovePresetClicked);
			this.btnPlayPreset.Clicked += new global::System.EventHandler (this.OnBtnPlayPresetClicked);
			this.btnMiddle.Clicked += new global::System.EventHandler (this.OnBtnMiddleClicked);
			this.btnLeft.Pressed += new global::System.EventHandler (this.OnBtnLeftPressed);
			this.btnLeft.Released += new global::System.EventHandler (this.OnBtnLeftReleased);
			this.btnBottomRight.Pressed += new global::System.EventHandler (this.OnBtnBottomRightPressed);
			this.btnBottomRight.Released += new global::System.EventHandler (this.OnBtnBottomRightReleased);
			this.btnBottomLeft.Pressed += new global::System.EventHandler (this.OnBtnBottomLeftPressed);
			this.btnBottomLeft.Released += new global::System.EventHandler (this.OnBtnBottomLeftReleased);
			this.btnBottom.Pressed += new global::System.EventHandler (this.OnBtnBottomPressed);
			this.btnBottom.Released += new global::System.EventHandler (this.OnBtnBottomReleased);
			this.btnAddPreset.Clicked += new global::System.EventHandler (this.OnBtnAddPresetClicked);
		}
	}
}
