
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class SettingsDialog
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.ComboBox cmbLanguage;
		
		private global::Gtk.Label lblLanguage;
		
		private global::Gtk.Label lblMPlayer;
		
		private global::Gtk.Label lblMPlayerParams;
		
		private global::Gtk.Entry txtMPlayer;
		
		private global::Gtk.Entry txtMPlayerParams;
		
		private global::Gtk.Label lblDefault;
		
		private global::Gtk.Button btnCancel;
		
		private global::Gtk.Button btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.SettingsDialog
			this.Name = "xCom.CamManager.SettingsDialog";
			this.Title = "Settings";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DestroyWithParent = true;
			// Internal child xCom.CamManager.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.cmbLanguage = global::Gtk.ComboBox.NewText ();
			this.cmbLanguage.AppendText ("English");
			this.cmbLanguage.AppendText ("Deutsch");
			this.cmbLanguage.Name = "cmbLanguage";
			this.table1.Add (this.cmbLanguage);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.cmbLanguage]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblLanguage = new global::Gtk.Label ();
			this.lblLanguage.Name = "lblLanguage";
			this.lblLanguage.Xalign = 0F;
			this.lblLanguage.LabelProp = "Language";
			this.table1.Add (this.lblLanguage);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblLanguage]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblMPlayer = new global::Gtk.Label ();
			this.lblMPlayer.Name = "lblMPlayer";
			this.lblMPlayer.Xalign = 0F;
			this.lblMPlayer.LabelProp = "MPlayer Location";
			this.table1.Add (this.lblMPlayer);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblMPlayer]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblMPlayerParams = new global::Gtk.Label ();
			this.lblMPlayerParams.Name = "lblMPlayerParams";
			this.lblMPlayerParams.Xalign = 0F;
			this.lblMPlayerParams.LabelProp = "MPlayer Params";
			this.table1.Add (this.lblMPlayerParams);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblMPlayerParams]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtMPlayer = new global::Gtk.Entry ();
			this.txtMPlayer.CanFocus = true;
			this.txtMPlayer.Name = "txtMPlayer";
			this.txtMPlayer.IsEditable = true;
			this.txtMPlayer.InvisibleChar = '●';
			this.table1.Add (this.txtMPlayer);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtMPlayer]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtMPlayerParams = new global::Gtk.Entry ();
			this.txtMPlayerParams.CanFocus = true;
			this.txtMPlayerParams.Name = "txtMPlayerParams";
			this.txtMPlayerParams.IsEditable = true;
			this.txtMPlayerParams.InvisibleChar = '●';
			this.table1.Add (this.txtMPlayerParams);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtMPlayerParams]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table1);
			// Notebook tab
			this.lblDefault = new global::Gtk.Label ();
			this.lblDefault.Name = "lblDefault";
			this.lblDefault.LabelProp = "Default";
			this.notebook1.SetTabLabel (this.table1, this.lblDefault);
			this.lblDefault.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child xCom.CamManager.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanDefault = true;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.btnCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.btnCancel]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.CanDefault = true;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseStock = true;
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = "gtk-ok";
			this.AddActionWidget (this.btnOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.btnOk]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.Response += new global::Gtk.ResponseHandler (this.OnResponse);
			this.cmbLanguage.Changed += new global::System.EventHandler (this.OnCmbLanguageChanged);
		}
	}
}
