
// This file has been generated by the GUI designer. Do not modify.
namespace xCom.CamManager
{
	public partial class CamInfo
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Label lblDeviceName;
		
		private global::Gtk.Label lblDeviceNameData;
		
		private global::Gtk.Label lblFirmwareVersion;
		
		private global::Gtk.Label lblFirmwareVersionData;
		
		private global::Gtk.Label lblHardwareVersion;
		
		private global::Gtk.Label lblHardwareVersionData;
		
		private global::Gtk.Label lblIsMainStream;
		
		private global::Gtk.Label lblIsMainStreamData;
		
		private global::Gtk.Label lblMac;
		
		private global::Gtk.Label lblMacData;
		
		private global::Gtk.Label lblProductName;
		
		private global::Gtk.Label lblProductNameData;
		
		private global::Gtk.Label lblSerialNumber;
		
		private global::Gtk.Label lblSerialNumberData;
		
		private global::Gtk.Label lblStreamKind;
		
		private global::Gtk.Label lblStreamKindData;
		
		private global::Gtk.Label lblStreamMode;
		
		private global::Gtk.Label lblStreamModeData;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xCom.CamManager.CamInfo
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xCom.CamManager.CamInfo";
			// Container child xCom.CamManager.CamInfo.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(9)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.lblDeviceName = new global::Gtk.Label ();
			this.lblDeviceName.Name = "lblDeviceName";
			this.lblDeviceName.Xalign = 0F;
			this.lblDeviceName.LabelProp = "Device Name";
			this.table1.Add (this.lblDeviceName);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblDeviceName]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblDeviceNameData = new global::Gtk.Label ();
			this.lblDeviceNameData.Name = "lblDeviceNameData";
			this.lblDeviceNameData.Xalign = 0F;
			this.table1.Add (this.lblDeviceNameData);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblDeviceNameData]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblFirmwareVersion = new global::Gtk.Label ();
			this.lblFirmwareVersion.Name = "lblFirmwareVersion";
			this.lblFirmwareVersion.Xalign = 0F;
			this.lblFirmwareVersion.LabelProp = "Firmware Version";
			this.table1.Add (this.lblFirmwareVersion);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblFirmwareVersion]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblFirmwareVersionData = new global::Gtk.Label ();
			this.lblFirmwareVersionData.Name = "lblFirmwareVersionData";
			this.lblFirmwareVersionData.Xalign = 0F;
			this.table1.Add (this.lblFirmwareVersionData);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblFirmwareVersionData]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblHardwareVersion = new global::Gtk.Label ();
			this.lblHardwareVersion.Name = "lblHardwareVersion";
			this.lblHardwareVersion.Xalign = 0F;
			this.lblHardwareVersion.LabelProp = "Hardware Version";
			this.table1.Add (this.lblHardwareVersion);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblHardwareVersion]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblHardwareVersionData = new global::Gtk.Label ();
			this.lblHardwareVersionData.Name = "lblHardwareVersionData";
			this.lblHardwareVersionData.Xalign = 0F;
			this.table1.Add (this.lblHardwareVersionData);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblHardwareVersionData]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblIsMainStream = new global::Gtk.Label ();
			this.lblIsMainStream.Name = "lblIsMainStream";
			this.lblIsMainStream.Xalign = 0F;
			this.lblIsMainStream.LabelProp = "Is MainStream Mode";
			this.table1.Add (this.lblIsMainStream);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblIsMainStream]));
			w7.TopAttach = ((uint)(6));
			w7.BottomAttach = ((uint)(7));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblIsMainStreamData = new global::Gtk.Label ();
			this.lblIsMainStreamData.Name = "lblIsMainStreamData";
			this.lblIsMainStreamData.Xalign = 0F;
			this.table1.Add (this.lblIsMainStreamData);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblIsMainStreamData]));
			w8.TopAttach = ((uint)(6));
			w8.BottomAttach = ((uint)(7));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblMac = new global::Gtk.Label ();
			this.lblMac.Name = "lblMac";
			this.lblMac.Xalign = 0F;
			this.lblMac.LabelProp = "Mac";
			this.table1.Add (this.lblMac);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblMac]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblMacData = new global::Gtk.Label ();
			this.lblMacData.Name = "lblMacData";
			this.lblMacData.Xalign = 0F;
			this.table1.Add (this.lblMacData);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblMacData]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblProductName = new global::Gtk.Label ();
			this.lblProductName.Name = "lblProductName";
			this.lblProductName.Xalign = 0F;
			this.lblProductName.LabelProp = "ProductName";
			this.table1.Add (this.lblProductName);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblProductName]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblProductNameData = new global::Gtk.Label ();
			this.lblProductNameData.Name = "lblProductNameData";
			this.lblProductNameData.Xalign = 0F;
			this.table1.Add (this.lblProductNameData);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblProductNameData]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblSerialNumber = new global::Gtk.Label ();
			this.lblSerialNumber.Name = "lblSerialNumber";
			this.lblSerialNumber.Xalign = 0F;
			this.lblSerialNumber.LabelProp = "Serial Number";
			this.table1.Add (this.lblSerialNumber);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblSerialNumber]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblSerialNumberData = new global::Gtk.Label ();
			this.lblSerialNumberData.Name = "lblSerialNumberData";
			this.lblSerialNumberData.Xalign = 0F;
			this.table1.Add (this.lblSerialNumberData);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblSerialNumberData]));
			w14.TopAttach = ((uint)(5));
			w14.BottomAttach = ((uint)(6));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStreamKind = new global::Gtk.Label ();
			this.lblStreamKind.Name = "lblStreamKind";
			this.lblStreamKind.Xalign = 0F;
			this.lblStreamKind.LabelProp = "Stream Kind";
			this.table1.Add (this.lblStreamKind);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStreamKind]));
			w15.TopAttach = ((uint)(7));
			w15.BottomAttach = ((uint)(8));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStreamKindData = new global::Gtk.Label ();
			this.lblStreamKindData.Name = "lblStreamKindData";
			this.lblStreamKindData.Xalign = 0F;
			this.table1.Add (this.lblStreamKindData);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStreamKindData]));
			w16.TopAttach = ((uint)(7));
			w16.BottomAttach = ((uint)(8));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStreamMode = new global::Gtk.Label ();
			this.lblStreamMode.Name = "lblStreamMode";
			this.lblStreamMode.Xalign = 0F;
			this.lblStreamMode.LabelProp = "Stream Mode";
			this.table1.Add (this.lblStreamMode);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStreamMode]));
			w17.TopAttach = ((uint)(8));
			w17.BottomAttach = ((uint)(9));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStreamModeData = new global::Gtk.Label ();
			this.lblStreamModeData.Name = "lblStreamModeData";
			this.lblStreamModeData.Xalign = 0F;
			this.table1.Add (this.lblStreamModeData);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStreamModeData]));
			w18.TopAttach = ((uint)(8));
			w18.BottomAttach = ((uint)(9));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
